### PR TITLE
chore: bump version number to v0.5.0

### PR DESCRIPTION
**Pull request by danielolsen**
[Pull Request doc](https://breakthrough-energy.github.io/docs/user/git_guide.html#d-pull-request)

### Purpose
Companion to #308.

### Time estimate
5 seconds.

### CODE REVIEW

**Review by rouille — APPROVED** [review]

**Review by rouille — APPROVED** [review]
Thanks

**Comment by jon-hagg** [comment]
Think we need to update this PR or make a new one, since the version moved to setup.cfg.

**Comment by danielolsen** [comment]
> Think we need to update this PR or make a new one, since the version moved to setup.cfg.

Done.

**Review by jon-hagg — APPROVED** [review]
Thanks

**Review by kasparm — APPROVED** [review]
Thanks

**Pull request merged**
