### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jon-hagg**
### Summary of changes

- Additions
```
  {}
```
- Deletions
```
  {}
```
- Updates
```
  {
  "cffi": "1.14.4 -> 1.14.5",
  "cryptography": "3.3.1 -> 3.4.6",
  "jinja2": "2.11.2 -> 2.11.3",
  "matplotlib": "3.3.3 -> 3.3.4",
  "more-itertools": "8.6.0 -> 8.7.0",
  "numpy": "1.19.5 -> 1.20.1",
  "packaging": "20.8 -> 20.9",
  "pandas": "1.1.5 -> 1.2.2",
  "pytz": "2020.5 -> 2021.1",
  "pyyaml": "5.3.1 -> 5.4.1",
  "scipy": "1.6.0 -> 1.6.1",
  "tqdm": "4.56.0 -> 4.58.0",
  "urllib3": "1.26.2 -> 1.26.3"
}
```

Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request

### CODE REVIEW

**Comment by jon-hagg** [comment]
Keeping this one, now that the workflow is checked in.

**Comment by jon-hagg** [comment]
Not sure what our process would suggest here, but I think I can merge this? In this case at least, I believe the updates are for consistency with powersimdata. @kasparm FYI

**Comment by rouille** [comment]
> Not sure what our process would suggest here, but I think I can merge this? In this case at least, I believe the updates are for consistency with powersimdata. @kasparm FYI
> 
> edit: lol I can't approve "my own" changes. We should probably create a separate account for automation anyway.

It looks like I can merge it as an administrator. I thought you were one too.

**Comment by jon-hagg** [comment]
Yeah I could but wanted to have an approval on it. Could you approve/merge this time? I will make an issue to look into the correct way to do this.

**Review by rouille — APPROVED** [review]
All good

**Pull request merged**
