### PR TITLE
Merge develop into master for v0.5.2 release

### PR DESCRIPTION
**Pull request by rouille**
### Purpose
Merge `develop` into `master` for 0.5.2 release

#### Closed issues
*  Improve code coverage (#338) 

#### Merged Pull Requests (features)
None

#### Merged Pull Requests (fixes, etc.)
* chore: bump version to 0.5.2  by @rouille in #347
* Update PowerSimData version by @rouille in #346
* chore(deps): bump pillow from 9.1.0 to 9.1.1 in #345
* Remove dependency on ScenarioInfo objects by @rouille in #344
* ci: trigger stable image build by @jenhagg  #343
* Update dependencies in #342
* docs: describe scenarios used in the tutorial by @rouille in #340
* Improve code coverage by @rouille in #337
* chore(deps): bump paramiko from 2.9.2 to 2.10.1 and bokeh from 2.0.2 to 2.4.2 in #335
* chore: remove obsolete module by @rouille in #336
* Clean up tox file and fix warnings by @rouille in #334
* chore: remove issue and pull request template so default takes effect by @kasparm in #333

### CODE REVIEW

**Review by BainanXia — APPROVED** [review]

**Comment by jenhagg** [comment]
How did you generate the release notes?

**Review by jenhagg — APPROVED** [review]

**Comment by jenhagg** [comment]
> > How did you generate the release notes?
> > By hand, copying/pasting closed PRs and issues
> 
> Shouldn't it be generated automatically by Github?

The way I do it is first using a custom `git log` command to get a sorted commit list (just to provide something useful). Then once develop ->  master is merged, auto generate the release notes from the releases UI and update the PR description. Not sure if there is a better way, e.g. basing releases off develop or something.

**Comment by rouille** [comment]
> > > How did you generate the release notes?
> > > By hand, copying/pasting closed PRs and issues
> > 
> > 
> > Shouldn't it be generated automatically by Github?
> 
> The way I do it is first using a custom `git log` command to get a sorted commit list (just to provide something useful). Then once develop -> master is merged, auto generate the release notes from the releases UI and update the PR description. Not sure if there is a better way, e.g. basing releases off develop or something.

I believe I always did some copy/paste. It would be nice to automate the process so this is consistent across release and packages.

**Comment by jenhagg** [comment]
> I believe I always did some copy/paste. It would be nice to automate the process so this is consistent across release and packages.

I'll look into it, been meaning to do that for a while.

**Comment by BainanXia** [comment]
> > I believe I always did some copy/paste. It would be nice to automate the process so this is consistent across release and packages.
> 
> I'll look into it, been meaning to do that for a while.

I never did it before but [this](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) is what I looked into before.

**Pull request merged**
