### PR TITLE
Update packaging and docker related workflows

### PR DESCRIPTION
**Pull request by jon-hagg**
### Purpose
Add the necessary bits to publish to PyPI and remove soon to be obsolete docker build.

### What the code is doing
A few things are combined here for continuity:
- new workflow to build and publish package to PyPI on new tags
- remove docker build which is moved to plug, pending https://github.com/Breakthrough-Energy/plug/pull/25
- specify the version of powersimdata to be installed from PyPI

For context, once we restrict the powersimdata version, the docker build as-is will no longer make sense - the image is inheriting from `powersimdata:latest` but then we will override that with whatever version matches the specifier. 

### Testing
Built the package locally, but mostly this is copy-paste from elsewhere.

### Time estimate
15 min

### CODE REVIEW

**Comment by rouille** [comment]
We will publish PreREISE and PostREISE on PyPi too?

**Comment by jon-hagg** [comment]
Support for building a "stable" docker image based on the latest published version of postreise is included in this draft PR https://github.com/Breakthrough-Energy/plug/pull/29

**Review by rouille — APPROVED** [review]
LGTM. We might want to update the PowerSimData version after it is released to 0.4.4

**Review by rouille — APPROVED** [review]
Still looks good

**Pull request merged**
