### PR TITLE
ci: add coverage report to pytest

### PR DESCRIPTION
**Pull request by jon-hagg**
### Purpose
Identical to Breakthrough-Energy/PowerSimData#471 except didn't add python 3.9 testing since pyproj is incompatible, so will address that separately

### CODE REVIEW

**Comment by rouille** [comment]
Ah. 32%.

**Review by rouille — APPROVED** [review]
It is super useful to see where we are lacking

**Comment by danielolsen** [comment]
> It is super useful to see where we are lacking

Pretty much as expected: `postreise.analyze` is pretty good, but there's almost no coverage of `postreise.plot`.

**Comment by BainanXia** [comment]
> > It is super useful to see where we are lacking
> 
> Pretty much as expected: `postreise.analyze` is pretty good, but there's almost no coverage of `postreise.plot`.

Write test functions to run notebooks could increase the coverage of the plot module or we can look into the axes object that the plot function returns.

**Pull request merged**
