### PR TITLE
ci: update some packages, and add workflow to automate package updates

### PR DESCRIPTION
**Pull request by jon-hagg**
### Purpose
Define a new workflow that will regenerate Pipfile.lock and create a PR with the changes. The `workflow_dispatch` trigger allows manually running by clicking a button, or via a webhook from PowerSimData (leaning toward keeping it manual for now). 

### What the code is doing
* Define the workflow, using the `update-packages` action from our new actions repo, and the `create-pull-request` action from the community. 
* Updated a couple packages to be consistent with PowerSimData. 

### Testing
Ran a nearly identical workflow from the `jon/test` branch and the PR was created.

### Time estimate
5 min

### CODE REVIEW

**Comment by rouille** [comment]
who is Peter Evans?

**Comment by jon-hagg** [comment]
> who is Peter Evans?

Dunno, just found the [repository](https://github.com/peter-evans/create-pull-request) via google. Seems legit, and saves a bunch of work.

**Comment by rouille** [comment]
> > who is Peter Evans?
> 
> Dunno, just found the [repository](https://github.com/peter-evans/create-pull-request) via google. Seems legit, and saves a bunch of work.

Indeed, the repository is pretty big. It has a MIT license so we should be good.

**Comment by jon-hagg** [comment]
> > > who is Peter Evans?
> > 
> > 
> > Dunno, just found the [repository](https://github.com/peter-evans/create-pull-request) via google. Seems legit, and saves a bunch of work.
> 
> Indeed, the repository is pretty big. It has a MIT license so we should be good.

Yeah I figured we're ok since we aren't distributing the code? The only other aspect would be whether it's secure, which I guess is a similar risk as pulling in package updates. Could always fork to be sure, but I figured the risk is tolerable (open to debate though).

**Review by rouille — APPROVED** [review]
Let's test it

**Pull request merged**
